package github

import (
	"fmt"
)

// PluginName is the name used in selectors generated by this plugin.
const PluginName = "github-actions"

// Selector represents a SPIRE selector as a type:value pair.
type Selector struct {
	Type  string
	Value string
}

// String returns the selector in "type:value" format.
func (s Selector) String() string {
	return fmt.Sprintf("%s:%s", s.Type, s.Value)
}

// BuildSelectors generates SPIRE selectors from GitHub Actions OIDC claims.
// Only non-empty claim values are included.
func BuildSelectors(claims *Claims) []Selector {
	var selectors []Selector

	add := func(key, value string) {
		if value != "" {
			selectors = append(selectors, Selector{
				Type:  PluginName,
				Value: fmt.Sprintf("%s:%s", key, value),
			})
		}
	}

	// Core identity selectors.
	add("repository", claims.Repository)
	add("repository_owner", claims.RepositoryOwner)
	add("repository_id", claims.RepositoryID)
	add("repository_owner_id", claims.RepositoryOwnerID)
	add("repository_visibility", claims.RepositoryVisibility)

	// Workflow selectors.
	add("workflow", claims.Workflow)
	add("workflow_ref", claims.WorkflowRef)
	add("job_workflow_ref", claims.JobWorkflowRef)

	// Git ref selectors.
	add("ref", claims.Ref)
	add("ref_type", claims.RefType)
	add("sha", claims.SHA)
	if claims.HeadRef != "" {
		add("head_ref", claims.HeadRef)
	}
	if claims.BaseRef != "" {
		add("base_ref", claims.BaseRef)
	}

	// Trigger selectors.
	add("event_name", claims.EventName)
	add("actor", claims.Actor)
	add("actor_id", claims.ActorID)

	// Run selectors.
	add("run_id", claims.RunID)
	add("run_number", claims.RunNumber)
	add("run_attempt", claims.RunAttempt)

	// Environment (only present for deployment jobs).
	add("environment", claims.Environment)

	// Runner selectors.
	add("runner_environment", claims.RunnerEnvironment)

	return selectors
}

// AgentID generates the SPIFFE agent ID path from claims and the trust domain.
// Format: spiffe://<trust-domain>/spire/agent/github_actions/<repository>
func AgentID(trustDomain, repository string) string {
	return fmt.Sprintf("spiffe://%s/spire/agent/github_actions/%s", trustDomain, repository)
}
